[DRAFT] add visit count and route to see most visited items
begumnurak/Webprogrammierung pull request #5
Opened 2023-03-06 17:35 UTC by onesimpledot

2023-03-15 15:16 UTC, GrafBunsen requested changes
"Am meisten angesehen" wird nicht angezeigt wenn man keine Rezepte als Favoriten hat. Man bekommt nur die Fehlermeldung "Es wurden keine favorisierten Rezepte gefunden." Das muss noch irgendwie getrennt werden

2023-03-15 15:27 UTC, emsbe commented
> "Am meisten angesehen" wird nicht angezeigt wenn man keine Rezepte als Favoriten hat. Man bekommt nur die Fehlermeldung "Es wurden keine favorisierten Rezepte gefunden." Das muss noch irgendwie getrennt werden

Fixed

2023-03-15 15:36 UTC, GrafBunsen requested changes
Most viewed and favorites should be displayed on landing page

2023-03-18 07:27 UTC, GrafBunsen approved these changes

2023-03-18 11:28 UTC, merged